export const catalog = [
  { title: "Trending", filter: "/api/show/trending" },
  { title: "Popular", filter: "/api/show/popular" },
  { title: "Recent (Sub)", filter: "/api/show/recent?type=sub" },
  { title: "Recent (Dub)", filter: "/api/show/recent?type=dub" },
  { title: "Recent (Chinese)", filter: "/api/show/recent?type=chinese" },
  { title: "All Anime", filter: "/api/anime" },
];

export const genres = [
  { title: "Action", filter: "Action" },
  { title: "Adventure", filter: "Adventure" },
  { title: "Comedy", filter: "Comedy" },
  { title: "Drama", filter: "Drama" },
  { title: "Ecchi", filter: "Ecchi" },
  { title: "Fantasy", filter: "Fantasy" },
  { title: "Horror", filter: "Horror" },
  { title: "Mahou Shoujo", filter: "Mahou Shoujo" },
  { title: "Mecha", filter: "Mecha" },
  { title: "Music", filter: "Music" },
  { title: "Mystery", filter: "Mystery" },
  { title: "Psychological", filter: "Psychological" },
  { title: "Romance", filter: "Romance" },
  { title: "Sci-Fi", filter: "Sci-Fi" },
  { title: "Slice of Life", filter: "Slice of Life" },
  { title: "Sports", filter: "Sports" },
  { title: "Supernatural", filter: "Supernatural" },
  { title: "Suspense", filter: "Suspense" },
  { title: "Thriller", filter: "Thriller" },
];
